server:
  port: 8888

logging:
  level:
    ROOT: info

spring:
  application:
    name: simple-javaspringboot

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:23306/simple?useUnicode=true&characterEncoding=UTF-8&tinyInt1isBit=false
    username: root
    password: 11111111
  jpa:
    hibernate:
      ddl-auto: update

key: test1111

#payment:
#  linepay:
#    channel-id: 1579416885
#    channel-secret: 4c59cc25d8c3641c0ed237ed1edc0d7f
#    url: http://api.powerplusit.com/v1/line/api
#    currency: THB
#    product-name: Power plus
#    confirm-url-type: SERVER
#    confirm-url: https://api-sit.powerplusit.com/v1/powerplus/appapi/pay/handleLineReturn?orderId={orderId}
#    success-url: https://api-sit.powerplusit.com/v1/payment/linepay/success?status={status}&orderCode={orderId}
#    failure-url: https://api-sit.powerplusit.com/v1/payment/linepay/success?status={status}&orderCode={orderId}
#  paypal:
#    url: https://api.paypal.com
#    mode: live
#    client:
#      id: AaUsi2IpzAm5IV7GZDdcVL73YOM2-mHyBgQx7Z_y8WikspqY4BCz8xTJDTfXwJEyWBih5ZsRtm9MhXPe
#      secret: EANFLVxmwTQgLE9Uit9VH22W4QjHi9AOd__SiOBNgzd0YBmLQZMx28I3V0YQEK604s7osBnohkVEQL07
#    description: Power plus
#    currency: THB
#    cancel-url: https://www.powerplusit.com/
#    success-url: https://api-sit.powerplusit.com/v1/powerplus/appapi/pay/handleReturnPaypal
#  scb2c2p:
#    merchant-id: JT04
#    api-secret: QnmrnH6QE23N
#    redirect:
#      payment-url: https://demo2.2c2p.com/2C2PFrontEnd/RedirectV3/payment
#      version: 8.5
#      payment-description: POWER PLUS
#      currency: 764
#      # todo: this one not handle payment yet
#      result-url-1: https://api-sit.powerplusit.com/v1/payment/scb2c2p/redirectResult
#    redirects:
#      deeplink-url: https://api-sit.powerplusit.com/v1/scb2c2p/redirect.html?profile=sit&orderId={orderId}&amount={money}
#      success-url: https://api-sit.powerplusit.com/v1/payment/scb2c2p/success.html
#      failure-url: https://api-sit.powerplusit.com/v1/payment/scb2c2p/failure.html
#  scbeasy:
#    api-key: l7c1634f7f8d4f45c889c308349b7c2c55
#    api-secret: 29a0251f83744020919fd2aa6aabefd0
#    api-url: https://api-sandbox.partners.scb/partners/sandbox
#    account-id: 952839489658767
#    merchant-id: 147645385517229
#    terminal-id: 398764234183322
#    callback-url: https://api-sit.powerplusit.com/v1/scbeasy/payment/result
#    ref3: KRI

#images:
#  url: https://api-sit.powerplusit.com/v1/powerplus/images
#scheduler:
#  key: 12345678
#security-key: pxoxwxexrxpxlxuxsxsxixt
#login:
#  business:
#    enabled: false
