server:
  port: 8888

logging:
  level:
    ROOT: info

spring:
  application:
    name: simple-javaspringboot

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:23306/simple?useUnicode=true&characterEncoding=UTF-8&tinyInt1isBit=false
    username: root
    password: 11111111
  jpa:
    hibernate:
      ddl-auto: update

key: test1111
